spring.application.name=arbitrage
# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:mariadb://localhost:3307/arb
spring.datasource.username=arb_user
spring.datasource.password=arb_password
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# ===============================
# JPA & HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true

# ===============================
# DISRUPTOR CONFIGURATION
# ===============================
disruptor.buffer-size=4096
disruptor.wait-strategy=busy-spin
disruptor.producer-type=multi

# ===============================
# LOGGING
# ===============================
logging.level.root=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ===============================
# ALOR CONFIGURATION
# ===============================
alor.moex-securities.SBER=TQBR
alor.moex-securities.GAZP=TQBR
alor.moex-securities.VTBR=TQBR
alor.moex-securities.YNDX=TQBR
alor.websocket.url=wss://api.alor.ru/ws
alor.refresh.url=https://oauth.alor.ru/refresh
alor.refresh.token=b6b9aadf-0bc6-419c-a1f2-e28e142e77ad
alor.refresh.interval=1440000
alor.subscription.cancel-check-interval=2000
alor.subscription.enabled=true

