cancel.subscription=true
instruments=NG-9.25:SPBFUT,NG-10.25:SPBFUT,INR-9.25:SPBFUT,INR-12.25:SPBFUT, SILV-9.25:SPBFUT,GL-9.25:SPBFUT,\
  GL-12.25:SPBFUT,ED-9.25:SPBFUT,ED-12.25:SPBFUT,Si-9.25:SPBFUT,Si-12.25:SPBFUT
#GAZP:TQBR,SBER:TQBR,VTBR:TQBR,
#NG-9.25:SPBFUT